### ISSUE TITLE
2.1.0 doesn't work without log level set to debug (maybe missing code)

### ISSUE THREAD

**Issue by MichaelMKenny** [Nonary/ResolutionAutomation#23]
The new pre-release version 2.1.0 doesn't seem to have all the changes necessary changes in the OnStreamStart function in ResolutionMatcher-Functions.ps1 file to change the resolution when the log level isn't debug. I thought this new version didn't need read the log, but when I turned my log level in Sunshine to info, the script stopped working.

I tracked down the issue to a call to OnStreamStart passing in width, height, and frequency params that don't exist in the OnStreamStart function. In the 2.1.0 release source code OnStreamStart just gets the resolution from Get-ClientResolution, which is just reading the log.

Maybe you just forgot to push changes to this function, but I wrote an updated version of OnStreamStart that uses the Sunshine environment variables that are passed in from the call site. And it works:

```
function OnStreamStart($width, $height, $frequency) {
    $expectedRes = @{
        Height  = $height
        Width   = $width
        Refresh = $frequency
    }
    Set-ScreenResolution -Width $expectedRes.Width -Height $expectedRes.Height -Freq $expectedRes.Refresh
    Assert-ResolutionChange -originalRes $expectedRes
}
```

**Comment by MichaelMKenny** [comment]
Looks like I need to also change code in Assert-ResolutionChange:

```
function Assert-ResolutionChange($originalRes) {
    for ($i = 0; $i -lt 12; $i++) {
        $currentRes = Join-Overrides -resolution (@{
            Height  = $env:SUNSHINE_CLIENT_HEIGHT
            Width   = $env:SUNSHINE_CLIENT_WIDTH
            Refresh = $env:SUNSHINE_CLIENT_FPS
        })
        if (($currentRes.Width -ne $originalRes.Width) -or ($currentRes.Height -ne $originalRes.Height) -or ($currentRes.Refresh -ne $originalRes.Refresh)) {
            # If the resolutions don't match, set the screen resolution to the current client's resolution
            Write-Host "The client resolution changed within the past 6 seconds, this implies the first time the resolution was changed may have been incorrect due to stale data"
            Write-Host "Original Requested Resolution: $($originalRes.Width) x $($originalRes.Height) x $($originalRes.Refresh)"
            Write-Host "Expected Requested Resolution: $($currentRes.Width) x $($currentRes.Height) x $($currentRes.Refresh)"
            Set-ScreenResolution $currentRes.Width $currentRes.Height $currentRes.Refresh
            break
        }
        # Wait for a while before checking the resolution again
        Start-Sleep -Milliseconds 500
    }
}
```

**Comment by MichaelMKenny** [comment]
I know it's not consistent in OnStreamStart I'm using the params passed in (which are the Sunshine environment variables), and then in Assert-ResolutionChange I'm just straight up using them directly. But I used the params in OnStreamStart because your call to it was passing them in, so I wanted to write the function to use them. You do what you think is best :)

**Comment by Nonary** [comment]
> Maybe you just forgot to push changes to this function, but I wrote an updated version of OnStreamStart that uses the Sunshine environment variables that are passed in from the call site. And it works

Kind of, this was more of a quick test release of Sunshine’s new feature. I am going to push the code again sometime tomorrow that essentially removes the Assert and Get-ClientResolution functions as they are obsolete now.

You are correct the intention for this new version is to move away from having to set the log level to debug. I’ll work on fixing this issue today :)

**Comment by MichaelMKenny** [comment]
Thanks for letting me know. I look forward to the push :)

**Comment by Nonary** [comment]
This should be resolved now, let me know if that is not the case

**Comment by MichaelMKenny** [comment]
It all looks good except the Join-Overrides function doesn't work because you forgot to change the if test to test the passed in $width, $height, and $refresh. It's still using $resolution.width, $resolution.height, $resolution.refresh.

$resolution still being used:
```
if ($widths[0].Value -eq $resolution.width -and $heights[0].Value -eq $resolution.height -and $refreshes[0].Value -eq $resolution.refresh) {
```

Corrected code using passed in variables:
```
if ($widths[0].Value -eq $width -and $heights[0].Value -eq $height -and $refreshes[0].Value -eq $refresh) {
```

**Comment by Nonary** [comment]
> It all looks good except the Join-Overrides function doesn't work because you forgot to change the if test to test the passed in $width, $height, and $refresh. It's still using $resolution.width, $resolution.height, $resolution.refresh.
> 
> $resolution still being used:
> 
> ```
> if ($widths[0].Value -eq $resolution.width -and $heights[0].Value -eq $resolution.height -and $refreshes[0].Value -eq $resolution.refresh) {
> ```
> 
> Corrected code using passed in variables:
> 
> ```
> if ($widths[0].Value -eq $width -and $heights[0].Value -eq $height -and $refreshes[0].Value -eq $refresh) {
> ```

Good point, this has been fixed in latest commit
